# simple dockerfile to test OCP s2i using Dockerfile 

FROM quay.io/dpkshetty/pyflask:v1 --platform=linux/amd64

# CMD ["/bin/bash", "-c", "sleep infinity"]
# CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
