# simple dockerfile to test OCP s2i using Dockerfile 

FROM --platform=linux/amd64 quay.io/dpkshetty/pyflask:v1

# CMD ["/bin/bash", "-c", "sleep infinity"]
# CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
